version: '3.8'

services:
  web:
    image: php:7.4-apache
    container_name: codeigniter4_web
    volumes:
      - ./src:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: codeigniter4_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: codeigniter4
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  composer:
    image: composer
    container_name: codeigniter4_composer
    volumes:
      - ./src:/app
    working_dir: /app
    command: ["composer", "install"]

volumes:
  db_data: