all:
  children:
  php-demo:
        children:
          manager:
            hosts:
              php-demo1:
                ansible_host: "192.168.0.156"
                ansible_user: "root"
                ansible_ssh_private_key_file: '{{ cluster_ssh_key }}'
                platform_environment: '{{ platform_environment }}'
